# Generated by Django 6.0.8 on 2026-09-11 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تأیید'), ('ACTIVE', 'فعال'), ('REJECTED', 'ردشده'), ('REVOKED', 'لغوشده')], db_index=True, default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='profiles.patientprofile')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='profiles.psychologistprofile')),
            ],
            options={
                'verbose_name': 'ارتباط',
                'verbose_name_plural': 'ارتباط\u200cها',
                'db_table': 'patient_psychologist_relationships',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'psychologist'), name='unique_patient_psychologist')],
            },
        ),
    ]
