# Generated by Django 6.0.8 on 2026-09-11 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن'), ('OTHER', 'سایر')], max_length=10, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/patients/')),
                ('bio', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پروفایل مراجع',
                'verbose_name_plural': 'پروفایل\u200cهای مراجعان',
                'db_table': 'patient_profiles',
            },
        ),
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='psychologist_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/psychologists/')),
                ('bio', models.TextField(blank=True, default='')),
                ('specialty', models.CharField(blank=True, default='', max_length=160)),
                ('professional_code', models.CharField(blank=True, default='', max_length=64)),
                ('verification_status', models.CharField(choices=[('REGISTERED', 'ثبت\u200cنام\u200cشده'), ('PENDING_VERIFICATION', 'در انتظار تأیید'), ('APPROVED', 'تأییدشده'), ('REJECTED', 'ردشده'), ('SUSPENDED', 'تعلیق\u200cشده')], db_index=True, default='REGISTERED', max_length=32)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('verification_note', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پروفایل روان\u200cشناس',
                'verbose_name_plural': 'پروفایل\u200cهای روان\u200cشناسان',
                'db_table': 'psychologist_profiles',
            },
        ),
        migrations.CreateModel(
            name='PsychologistAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='profiles.psychologistprofile')),
            ],
            options={
                'verbose_name': 'افتخار',
                'verbose_name_plural': 'افتخارات',
                'db_table': 'psychologist_achievements',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='verification-documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.psychologistprofile')),
            ],
            options={
                'verbose_name': 'مدرک تأیید',
                'verbose_name_plural': 'مدارک تأیید',
                'db_table': 'psychologist_verification_documents',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
