# Generated by Django 6.0.8 on 2026-09-11 12:54

import apps.catalog.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('ACTIVE', 'فعال'), ('ARCHIVED', 'بایگانی\u200cشده')], default='DRAFT', max_length=16)),
                ('coding_system', models.CharField(default='R-PAS', max_length=32)),
                ('methodology_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('source_document', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تعریف آزمون',
                'verbose_name_plural': 'تعریف آزمون\u200cها',
                'db_table': 'test_definitions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TestVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=16)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.testdefinition')),
            ],
            options={
                'verbose_name': 'نسخه آزمون',
                'verbose_name_plural': 'نسخه\u200cهای آزمون',
                'db_table': 'test_versions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('RESPONSE', 'پاسخ'), ('CLARIFICATION', 'روشن\u200cسازی')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('test_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='catalog.testversion')),
            ],
            options={
                'verbose_name': 'مرحله آزمون',
                'verbose_name_plural': 'مراحل آزمون',
                'db_table': 'test_phases',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('image_path', models.CharField(blank=True, default='', max_length=512)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('configuration', models.JSONField(default=apps.catalog.models.default_card_configuration)),
                ('image_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='media.mediaasset')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='catalog.testphase')),
                ('test_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='catalog.testversion')),
            ],
            options={
                'verbose_name': 'کارت آزمون',
                'verbose_name_plural': 'کارت\u200cهای آزمون',
                'db_table': 'test_cards',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='testversion',
            constraint=models.UniqueConstraint(fields=('test_definition', 'version'), name='unique_definition_version'),
        ),
        migrations.AddConstraint(
            model_name='testphase',
            constraint=models.UniqueConstraint(fields=('test_version', 'kind'), name='unique_version_phase_kind'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcard',
            constraint=models.UniqueConstraint(fields=('test_version', 'card_number'), name='unique_version_card_number'),
        ),
    ]
