# Generated by Django 6.0.8 on 2026-09-11 12:54

import apps.assessments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('algorithm_version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PROCESSING', 'در حال پردازش'), ('DONE', 'انجام\u200cشده'), ('FAILED', 'ناموفق')], default='PENDING', max_length=16)),
                ('raw_analysis_data', models.JSONField(blank=True, default=dict)),
                ('calculated_data', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تحلیل آزمون',
                'verbose_name_plural': 'تحلیل\u200cهای آزمون',
                'db_table': 'assessment_analyses',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.PositiveSmallIntegerField()),
                ('client_response_id', models.CharField(max_length=64)),
                ('sequence', models.PositiveIntegerField()),
                ('card_response_number', models.PositiveSmallIntegerField()),
                ('response_text', models.TextField()),
                ('server_started_at', models.DateTimeField()),
                ('server_submitted_at', models.DateTimeField()),
                ('client_started_at', models.DateTimeField(blank=True, null=True)),
                ('client_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('client_metadata', models.JSONField(blank=True, default=dict)),
                ('measurement_data', models.JSONField(default=apps.assessments.models.empty_measurements)),
                ('clarification', models.JSONField(blank=True, null=True)),
                ('coding', models.JSONField(blank=True, null=True)),
                ('coded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پاسخ آزمون',
                'verbose_name_plural': 'پاسخ\u200cهای آزمون',
                'db_table': 'assessment_responses',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'ایجادشده'), ('IN_PROGRESS', 'در حال اجرا'), ('PAUSED', 'متوقف\u200cشده'), ('COMPLETED', 'تکمیل\u200cشده'), ('ABANDONED', 'رهاشده'), ('CANCELLED', 'لغوشده')], db_index=True, default='CREATED', max_length=16)),
                ('current_step', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administration', models.JSONField(default=apps.assessments.models.empty_administration)),
            ],
            options={
                'verbose_name': 'جلسه آزمون',
                'verbose_name_plural': 'جلسات آزمون',
                'db_table': 'assessment_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('structured_result', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گزارش آزمون',
                'verbose_name_plural': 'گزارش\u200cهای آزمون',
                'db_table': 'assessment_reports',
            },
        ),
    ]
