# Generated by Django 6.0.8 on 2026-09-11 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('catalog', '0001_initial'),
        ('profiles', '0001_initial'),
        ('relationships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresponse',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='catalog.assessmentcard'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='coded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coded_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.testphase'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='current_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.assessmentcard'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='current_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.testphase'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='profiles.patientprofile'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='profiles.psychologistprofile'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='relationships.relationship'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='test_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='catalog.testdefinition'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='test_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='catalog.testversion'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentsession'),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='assessments.assessmentsession'),
        ),
        migrations.AddField(
            model_name='assessmentanalysis',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='assessments.assessmentsession'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['patient', 'status'], name='assessment__patient_0098eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresponse',
            constraint=models.UniqueConstraint(fields=('assessment', 'client_response_id'), name='unique_assessment_client_response'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresponse',
            constraint=models.UniqueConstraint(fields=('assessment', 'sequence'), name='unique_assessment_sequence'),
        ),
    ]
