# Generated by Django 6.0.8 on 2026-09-15 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PROCESSING', 'در حال پردازش'), ('DONE', 'انجام\u200cشده'), ('FAILED', 'ناموفق')], default='PENDING', max_length=16)),
                ('source', models.CharField(choices=[('AI', 'مدل زبانی'), ('LEXICON', 'واژه\u200cنامه\u200cی محلی')], default='LEXICON', max_length=16)),
                ('model_name', models.CharField(blank=True, default='', max_length=64)),
                ('items', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_detection', to='assessments.assessmentsession')),
            ],
            options={
                'verbose_name': 'تشخیص واژه\u200cهای محتوا',
                'verbose_name_plural': 'تشخیص\u200cهای واژه\u200cهای محتوا',
                'db_table': 'assessment_content_detections',
            },
        ),
    ]
