# Generated by Django 6.0.8 on 2026-09-11 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assets/')),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فایل رسانه',
                'verbose_name_plural': 'فایل\u200cهای رسانه',
                'db_table': 'media_assets',
                'ordering': ['storage_key'],
            },
        ),
    ]
